<?php

namespace AppBundle\Repository;

/**
 * VerbeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerbeRepository extends \Doctrine\ORM\EntityRepository
{
}
